### ISSUE TITLE
Missing suite name in the output

### ISSUE THREAD

**Issue by sprat** [fumiakiy/karma-tap-reporter#11]
Would be nice if the suite name appeared in the output: I mean, the comments starting with '#' in the tap output. And it may even be better if the brower name appeared as a suite name too.

**Comment by sprat** [comment]
I guess the problem lies in karma-tap as the `suite` array seems to be always empty in the input of karma-tap-reporter. I don't understand how you tested the code displaying the suite name... with another framework than karma-tap?

**Comment by fumiakiy** [comment]
This repository doesn't depend on `karma-tap`.

**Comment by sprat** [comment]
Yes I know but I didn't figure that this plugin could be used without karma-tap. I'll close this issue as it's not caused by karma-tap-reporter.

**Comment by bySabi** [comment]
@sprat this is solved now with pending PR´s:
- https://github.com/fumiakiy/karma-tap-reporter/pull/12
- https://github.com/tmcw-up-for-adoption/karma-tap/pull/15
